### ISSUE TITLE
Suggestions to call footprints?

### ISSUE THREAD

**Issue by YichaoOU** [Tarela/SELMA#1]
Hi,

Thanks for the nice tool. 

Now that I have `NAME_cleavage.bw`, how should I get a footprint bed file?

Also, are the values in `NAME_cleavage.bw` from different samples comparable (e.g., for differential footprint analysis)?

Thanks,
Yichao

**Comment by Tarela** [comment]
Hi Yichao, 

Thanks for trying our tool. Current version of SELMA didn't provide denovo genome-wide footprint detection. From our bench marking analysis we think HINT might provide the best denovo genome-wide footprint detection. Our cleavage.bw and biasExpect.bw can help you realize which position has the real cleavage signal (high in cleavage.bw but low in biasExpect.bw) and which position has false positive signal caused by cleavage bias (high in both cleavage.bw and biasExpect.bw). Instead of a denovo genome-wide footprint bed file, we recommend to focus on the genome-wide motif region as candidate regions for a footprint detection, which provide better prediction power of TF binding and easier for cleavage bias detection and correction. 

The cleavage.bw from different samples are comparable if you normalize them by considering the read depth (e.g., divided/normalized by the total reads count for the corresponding sample. The biasExpect.bw from different samples are comparable without any further action. 

Feel free to let me know if you have further questions/suggestions. And feel free to suggest any potential new function you expect for SELMA. 

Shawn.

**Comment by YichaoOU** [comment]
Thanks for the information!
